### ISSUE TITLE
Instances missing.

### ISSUE THREAD

**Issue by GregorySchwartz** [ocramz/sparse-linear-algebra#41]
I cannot find instances for Innerspace and AdditiveGroup for SpVector and there may be other missing instances for both SpVector and SpMatrix as well. They were present in previous versions, but not the latest. This prevents me from adding vectors or finding dot products.

**Comment by ocramz** [comment]
Hi @GregorySchwartz , thanks for the report! I'll fix it asap. Sorry for the incovenience

**Comment by GregorySchwartz** [comment]
Also, Normed instances are also missing.

**Comment by Jaxan** [comment]
I bumped into the same problem (see my ghci interaction below). As a workaround I am using version 0.2.9.7 now.

```
Prelude> :m + Numeric.LinearAlgebra.Sparse
Prelude Numeric.LinearAlgebra.Sparse> :m + Data.Sparse.SpMatrix
Prelude Numeric.LinearAlgebra.Sparse Data.Sparse.SpMatrix> let m = eye 1 :: SpMatrix Double
Prelude Numeric.LinearAlgebra.Sparse Data.Sparse.SpMatrix> lu m

<interactive>:4:1: error:
    • Couldn't match type ‘Numeric.LinearAlgebra.Class.Scalar
                             (Data.Sparse.SpVector.SpVector Double)’
                     with ‘Double’
        arising from a use of ‘lu’
    • In the expression: lu m
      In an equation for ‘it’: it = lu m
```

**Comment by chisui** [comment]
The problem seems to be that the CPP macros used to define class instances for `SpVector` don't work. CPP shouldn't really be used there anyway. You could either use template haskell to define the macro or create more general instances using the Language extensions `FlexibleInstances` and `UndecidableInstances`:

```haskell
instance RealFloat n => VectorSpace (SpVector n) where
    type (Scalar (SpVector n)) = n
    n *^ v = scale n v
```

**Comment by ocramz** [comment]
Thank you for the feedback and @chisui and @Jaxan , I'll do my best to publish a more stable version soon. Been quite busy at work in general last few months so open source kind of suffered. However I'm glad to know you use the library and I would gladly review & accept PRs if there's something you feel should be added/improved.

**Comment by ocramz** [comment]
@Jaxan indeed, 0.2.9.7 is the last version that uses `vector-space`. I dropped it because one of its dependencies (`Memo-trie`) broke with the Stackage LTS used by this library.

**Comment by ocramz** [comment]
I've deprecated 0.2.9.8 and 0.2.9.9 for now, as these were released in a hurry.

**Comment by Jaxan** [comment]
Uncommenting all the instances and doing some small fixes solves the issue (and the CPP parts work just fine). However, you probably commented those instances out for a reason. Before doing a PR, I would like to know what the design considerations are.
