### ISSUE TITLE
unnecessary insertion 

### ISSUE THREAD

**Issue by AlexanderKoshkarov** [ocramz/sparse-linear-algebra#5]
in src/Math/Linear/Sparse/IntMap.hs:

insertIM2 ::
  IM.Key -> IM.Key -> a -> IM.IntMap (IM.IntMap a) -> IM.IntMap (IM.IntMap a)

insertIM2 i j x imm = IM.insert i **(IM.insert j x ro)** imm 
  where ro = maybe (IM.singleton j x) **(IM.insert j x)** (IM.lookup i imm)

don't you insert two times? It probably will make it slower.
maybe something like this?

insertIM2 ::
  IM.Key -> IM.Key -> a -> IM.IntMap (IM.IntMap a) -> IM.IntMap (IM.IntMap a)

insertIM2 i j x imm = IM.insert i ro imm 
  where ro = maybe (IM.singleton j x) (IM.insert j x) (IM.lookup i imm)

**Comment by ocramz** [comment]
Good catch! I've fixed it now, thanks Alex ^_^ I definitely have to ditch indices and move on to manipulating Traversables
