### ISSUE TITLE
Mat-vec multiplication for complex vector spaces is incorrect

### ISSUE THREAD

**Issue by Jaxan** [ocramz/sparse-linear-algebra#50]
https://github.com/ocramz/sparse-linear-algebra/blob/171f23036b3c744825862b4458a7ac19e483fa02/src/Data/Sparse/Common.hs#L238

Here, the function `dot = (<.>)` from the class `InnerSpace` is used. For complex vector spaces this is implemented as a conjugated inner product. However, for matrix-vector multiplication the ordinary in-conjugated inner product should be used.

**Comment by leftaroundabout** [comment]
Highly related: https://github.com/conal/vector-space/issues/20
