### ISSUE TITLE
contractSub is not implemented in a sparse way

### ISSUE THREAD

**Issue by Jaxan** [ocramz/sparse-linear-algebra#56]
This is a performance issue. `contractSub` should be implemented using the sparse structure instead of mapping over `[0..n]`. I noticed that this is very costly when I was profiling code which uses LU-decomposition.

`contractSub` is implemented here:
https://github.com/ocramz/sparse-linear-algebra/blob/01637f6a311f78693b3e1ba9bd640e0737fe54ca/src/Data/Sparse/SpMatrix.hs#L851

**Comment by ocramz** [comment]
I think we can close this now! Thanks @Jaxan ! 💯
